# Generated by Django 5.2.17 on 2026-09-16 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contract_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingestion_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=500)),
                ('source_external_id', models.CharField(max_length=500)),
                ('pipeline_status', models.CharField(choices=[('discovered', 'discovered'), ('downloaded', 'downloaded'), ('extracted', 'extracted'), ('chunked', 'chunked'), ('classifying', 'classifying'), ('classified', 'classified'), ('failed', 'failed')], default='discovered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.contracttype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.ingestionsource')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.sector')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_contracts', to='core.user')),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pipeline_status'], name='contracts_pipelin_d5622a_idx'), models.Index(fields=['contract_type'], name='contracts_contrac_717dcf_idx'), models.Index(fields=['sector'], name='contracts_sector__ae044c_idx'), models.Index(fields=['source'], name='contracts_source__953c5d_idx'), models.Index(fields=['opened_by'], name='contracts_opened__f9ed8e_idx'), models.Index(fields=['source', 'source_external_id'], name='contracts_source__a58f2a_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_external_id'), name='unique_contract_source_external_id')],
            },
        ),
    ]
