# Generated by Django 5.2.17 on 2026-09-22 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Senior Legal Product Analyst', 'Senior Legal Product Analyst'), ('Legal Product Analyst', 'Legal Product Analyst'), ('Senior AI Engineer', 'Senior AI Engineer'), ('AI Engineer', 'AI Engineer'), ('Full Stack Developer', 'Full Stack Developer')], default='Legal Product Analyst', max_length=100),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.user')),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='user_sessio_token_7a1a38_idx'), models.Index(fields=['user', 'expires_at'], name='user_sessio_user_id_60f801_idx')],
            },
        ),
    ]
