# Generated by Django 5.2.17 on 2026-09-16 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_external_id', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('document_title', models.CharField(blank=True, max_length=500, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('drive_web_link', models.URLField(blank=True, default='', max_length=1000)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('source_modified_time', models.DateTimeField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'pending'), ('extracted', 'extracted'), ('extracted_with_warnings', 'extracted_with_warnings'), ('rejected', 'rejected'), ('failed', 'failed')], default='pending', max_length=32)),
                ('last_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.contract')),
                ('ingestion_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.ingestionsource')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_id', models.CharField(max_length=32)),
                ('level', models.PositiveIntegerField()),
                ('assigned_depth', models.IntegerField()),
                ('display_number', models.CharField(blank=True, max_length=64, null=True)),
                ('clause_title', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_path', models.CharField(blank=True, max_length=255, null=True)),
                ('full_path', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_compound_lead_in', models.BooleanField(default=False)),
                ('bonded_to_lead_in', models.CharField(blank=True, max_length=32, null=True)),
                ('child_count', models.PositiveIntegerField(default=0)),
                ('descendant_count', models.PositiveIntegerField(default=0)),
                ('sibling_index', models.PositiveIntegerField(default=1)),
                ('sibling_count', models.PositiveIntegerField(default=1)),
                ('is_leaf', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField()),
                ('dfs_index', models.PositiveIntegerField()),
                ('bfs_index', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('numbering_source', models.CharField(blank=True, max_length=64, null=True)),
                ('style', models.CharField(blank=True, max_length=128, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('conflict', models.BooleanField(default=False)),
                ('has_flags', models.BooleanField(default=False)),
                ('lead_in_child_ids', models.JSONField(blank=True, default=list)),
                ('ancestor_ids', models.JSONField(blank=True, default=list)),
                ('child_ids', models.JSONField(blank=True, default=list)),
                ('paragraph_ids', models.JSONField(blank=True, default=list)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='document_pipeline.extractedclause')),
            ],
            options={
                'db_table': 'extracted_clauses',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('extracted', 'extracted'), ('extracted_with_warnings', 'extracted_with_warnings'), ('rejected', 'rejected'), ('failed', 'failed')], max_length=32)),
                ('schema_version', models.CharField(max_length=16)),
                ('parser_build', models.CharField(blank=True, default='', max_length=64)),
                ('document_name', models.CharField(max_length=500)),
                ('document_title', models.CharField(blank=True, max_length=500, null=True)),
                ('extracted_at', models.DateTimeField()),
                ('content_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('md5_checksum', models.CharField(blank=True, default='', max_length=32)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('source_modified_time', models.DateTimeField(blank=True, null=True)),
                ('rejection', models.JSONField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('warning_codes', models.JSONField(blank=True, default=list)),
                ('has_warnings', models.BooleanField(default=False)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('timings_ms', models.JSONField(blank=True, default=dict)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('clause_count', models.PositiveIntegerField(default=0)),
                ('paragraph_count', models.PositiveIntegerField(default=0)),
                ('max_level', models.PositiveIntegerField(default=0)),
                ('flagged_clause_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('persist_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='document_pipeline.document')),
            ],
            options={
                'db_table': 'extraction_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedParagraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_order', models.PositiveIntegerField()),
                ('local_id', models.CharField(max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('source_paragraph_index', models.PositiveIntegerField()),
                ('segment_index', models.PositiveIntegerField(default=0)),
                ('bucket', models.CharField(max_length=32)),
                ('container', models.CharField(max_length=32)),
                ('is_clause_start', models.BooleanField(default=False)),
                ('numbering_source', models.CharField(blank=True, max_length=64, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('breadcrumbs', models.JSONField(blank=True, default=list)),
                ('table_position', models.JSONField(blank=True, null=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragraph_rows', to='document_pipeline.extractedclause')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='document_pipeline.extractionrun')),
            ],
            options={
                'db_table': 'extracted_paragraphs',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='extractedclause',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='document_pipeline.extractionrun'),
        ),
        migrations.CreateModel(
            name='PipelineStageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('discover', 'discover'), ('download', 'download'), ('parse', 'parse'), ('persist', 'persist'), ('chunk', 'chunk'), ('classify', 'classify'), ('embed', 'embed'), ('publish', 'publish')], max_length=32)),
                ('status', models.CharField(choices=[('started', 'started'), ('succeeded', 'succeeded'), ('succeeded_with_warnings', 'succeeded_with_warnings'), ('rejected', 'rejected'), ('failed', 'failed'), ('skipped', 'skipped')], max_length=32)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='document_pipeline.document')),
                ('extraction_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_logs', to='document_pipeline.extractionrun')),
            ],
            options={
                'db_table': 'pipeline_stage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['extraction_status'], name='doc_extract_status_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['ingestion_source', 'source_external_id'], name='doc_source_ext_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['contract'], name='doc_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='doc_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('ingestion_source', 'source_external_id'), name='unique_document_source_external_id'),
        ),
        migrations.AddIndex(
            model_name='extractionrun',
            index=models.Index(fields=['document', '-created_at'], name='run_doc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionrun',
            index=models.Index(fields=['status'], name='run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionrun',
            index=models.Index(fields=['content_sha256'], name='run_sha256_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionrun',
            constraint=models.UniqueConstraint(fields=('document', 'attempt'), name='unique_extraction_run_attempt'),
        ),
        migrations.AddConstraint(
            model_name='extractionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='unique_current_extraction_run'),
        ),
        migrations.AddIndex(
            model_name='extractedparagraph',
            index=models.Index(fields=['run', 'sequence_order'], name='para_run_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedparagraph',
            index=models.Index(fields=['clause', 'sequence_order'], name='para_clause_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedparagraph',
            index=models.Index(fields=['run', 'page_number'], name='para_run_page_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedparagraph',
            index=models.Index(fields=['run', 'bucket'], name='para_run_bucket_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractedparagraph',
            constraint=models.UniqueConstraint(fields=('run', 'sequence_order'), name='unique_para_sequence'),
        ),
        migrations.AddConstraint(
            model_name='extractedparagraph',
            constraint=models.UniqueConstraint(fields=('run', 'source_paragraph_index'), name='unique_para_source_index'),
        ),
        migrations.AddIndex(
            model_name='extractedclause',
            index=models.Index(fields=['run', 'order_index'], name='clause_run_order_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedclause',
            index=models.Index(fields=['run', 'dfs_index'], name='clause_run_dfs_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedclause',
            index=models.Index(fields=['run', 'level'], name='clause_run_level_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedclause',
            index=models.Index(fields=['run', 'confidence'], name='clause_run_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedclause',
            index=models.Index(condition=models.Q(('has_flags', True)), fields=['run', 'order_index'], name='clause_run_flagged_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedclause',
            index=models.Index(condition=models.Q(('conflict', True)), fields=['run', 'order_index'], name='clause_run_conflict_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractedclause',
            constraint=models.UniqueConstraint(fields=('run', 'local_id'), name='unique_clause_local_id'),
        ),
        migrations.AddConstraint(
            model_name='extractedclause',
            constraint=models.UniqueConstraint(fields=('run', 'order_index'), name='unique_clause_order'),
        ),
        migrations.AddIndex(
            model_name='pipelinestagelog',
            index=models.Index(fields=['document', '-created_at'], name='stagelog_doc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinestagelog',
            index=models.Index(fields=['stage', 'status'], name='stagelog_stage_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinestagelog',
            index=models.Index(fields=['extraction_run'], name='stagelog_run_idx'),
        ),
    ]
