# Generated by Django 5.2.17 on 2026-09-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='extractedparagraph',
            name='unique_para_source_index',
        ),
        migrations.AlterField(
            model_name='extractedclause',
            name='canonical_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedclause',
            name='clause_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedclause',
            name='full_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedclause',
            name='parent_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
