# Generated by Django 5.2.17 on 2026-09-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('document_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_parent_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source_parent_id'], name='doc_parent_idx'),
        ),
    ]
