# Generated by Django 5.2.17 on 2026-09-18 09:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pipeline', '0002_remove_extractedparagraph_unique_para_source_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=16)),
                ('applies_to', models.CharField(choices=[('clause', 'clause'), ('non_clause', 'non_clause')], max_length=16)),
                ('number', models.PositiveIntegerField()),
                ('key', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('definition', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'canonical_types',
                'ordering': ['version', 'sort_order'],
                'indexes': [models.Index(fields=['version', 'sort_order'], name='ctype_version_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('version', 'key'), name='unique_canonical_type_key'), models.UniqueConstraint(fields=('version', 'name'), name='unique_canonical_type_name'), models.UniqueConstraint(fields=('version', 'applies_to', 'number'), name='unique_canonical_type_number')],
            },
        ),
        migrations.CreateModel(
            name='ClassificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('running', 'running'), ('succeeded', 'succeeded'), ('succeeded_with_warnings', 'succeeded_with_warnings'), ('failed', 'failed')], default='running', max_length=32)),
                ('taxonomy_version', models.CharField(max_length=16)),
                ('prompt_version', models.CharField(max_length=16)),
                ('model_id', models.CharField(max_length=255)),
                ('bedrock_client', models.CharField(max_length=16)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('system_prompt_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('micro_count', models.PositiveIntegerField(default=0)),
                ('classified_count', models.PositiveIntegerField(default=0)),
                ('unclassified_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to='document_pipeline.chunkrun')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to='document_pipeline.document')),
            ],
            options={
                'db_table': 'classification_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_index', models.PositiveIntegerField()),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('chunk_ids', models.JSONField(default=list)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('succeeded', 'succeeded'), ('truncated', 'truncated'), ('refused', 'refused'), ('invalid', 'invalid')], max_length=16)),
                ('stop_reason', models.CharField(blank=True, default='', max_length=32)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('raw_output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='document_pipeline.classificationrun')),
            ],
            options={
                'db_table': 'classification_calls',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('classified', 'classified'), ('unclassified', 'unclassified'), ('failed', 'failed')], max_length=16)),
                ('label', models.CharField(blank=True, choices=[('Clause', 'Clause'), ('Non-clause', 'Non-clause')], max_length=16, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('expected_type_keys', models.JSONField(blank=True, default=list)),
                ('deviated', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('batch_index', models.PositiveIntegerField(default=0)),
                ('call_attempts', models.PositiveIntegerField(default=1)),
                ('raw_item', models.JSONField(blank=True, null=True)),
                ('validation_notes', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classifications', to='document_pipeline.canonicaltype')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='document_pipeline.chunk')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='document_pipeline.classificationrun')),
            ],
            options={
                'db_table': 'classifications',
            },
        ),
        migrations.CreateModel(
            name='CanonicalTypeAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=16)),
                ('alias', models.CharField(max_length=255)),
                ('match_key', models.CharField(max_length=255)),
                ('is_literal', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('canonical_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='document_pipeline.canonicaltype')),
            ],
            options={
                'db_table': 'canonical_type_aliases',
                'ordering': ['canonical_type', 'position'],
                'indexes': [models.Index(fields=['version', 'match_key'], name='ctalias_version_key_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_literal', True)), fields=('version', 'match_key'), name='unique_literal_alias_match_key'), models.UniqueConstraint(fields=('canonical_type', 'alias'), name='unique_alias_per_type')],
            },
        ),
        migrations.CreateModel(
            name='CanonicalTypeExclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('from_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='document_pipeline.canonicaltype')),
                ('to_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_from', to='document_pipeline.canonicaltype')),
            ],
            options={
                'db_table': 'canonical_type_exclusions',
                'ordering': ['from_type', 'position'],
                'constraints': [models.UniqueConstraint(fields=('from_type', 'to_type'), name='unique_type_exclusion'), models.CheckConstraint(condition=models.Q(('from_type', models.F('to_type')), _negated=True), name='type_exclusion_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='classificationrun',
            index=models.Index(fields=['document', '-created_at'], name='classrun_doc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationrun',
            index=models.Index(fields=['status'], name='classrun_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='classificationrun',
            constraint=models.UniqueConstraint(fields=('chunk_run', 'attempt'), name='unique_classification_run_attempt'),
        ),
        migrations.AddConstraint(
            model_name='classificationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('chunk_run',), name='unique_current_classification_run'),
        ),
        migrations.AddConstraint(
            model_name='classificationrun',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('status__in', ['succeeded', 'succeeded_with_warnings']), _connector='OR'), name='current_classification_run_finished'),
        ),
        migrations.AddIndex(
            model_name='classificationcall',
            index=models.Index(fields=['run', 'batch_index'], name='classcall_run_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['chunk'], name='class_chunk_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['run', 'canonical_type'], name='class_run_type_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(condition=models.Q(('needs_review', True)), fields=['run'], name='class_run_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.UniqueConstraint(fields=('run', 'chunk'), name='unique_classification_chunk'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('canonical_type__isnull', False), ('outcome', 'classified')), models.Q(models.Q(('outcome', 'classified'), _negated=True), ('canonical_type__isnull', True)), _connector='OR'), name='classification_type_iff_classified'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'unclassified'), _negated=True), ('label', 'Clause'), _connector='OR'), name='unclassified_is_clause'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confidence__isnull', True), ('label__isnull', True), ('outcome', 'failed')), models.Q(models.Q(('outcome', 'failed'), _negated=True), ('confidence__isnull', False), ('label__isnull', False)), _connector='OR'), name='classification_failed_has_no_answer'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('label', 'Non-clause'), _negated=True), ('sub_type__isnull', True), _connector='OR'), name='non_clause_has_no_sub_type'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), _connector='OR'), name='classification_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.CheckConstraint(condition=models.Q(('outcome', 'failed'), models.Q(('reason', ''), _negated=True), _connector='OR'), name='classification_has_reason'),
        ),
    ]
