# Generated by Django 5.2.17 on 2026-09-17 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pipeline', '0002_document_source_parent_id_document_doc_parent_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('chunker_version', models.CharField(blank=True, default='', max_length=16)),
                ('chunk_schema_version', models.CharField(max_length=16)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('macro_count', models.PositiveIntegerField(default=0)),
                ('micro_count', models.PositiveIntegerField(default=0)),
                ('indexed_count', models.PositiveIntegerField(default=0)),
                ('all_clauses_covered', models.BooleanField(default=False)),
                ('all_clauses_retrievable', models.BooleanField(default=False)),
                ('all_paragraphs_covered', models.BooleanField(default=False)),
                ('chunked_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_runs', to='document_pipeline.extractionrun')),
            ],
            options={
                'db_table': 'chunk_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('macro', 'macro'), ('micro', 'micro')], max_length=8)),
                ('order_index', models.PositiveIntegerField()),
                ('indexed_for_retrieval', models.BooleanField(default=False)),
                ('clause_identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('breadcrumb', models.TextField(blank=True, default='')),
                ('region', models.CharField(choices=[('body', 'body'), ('execution', 'execution'), ('exhibit', 'exhibit'), ('mixed', 'mixed')], default='body', max_length=32)),
                ('regions_included', models.JSONField(blank=True, default=list)),
                ('level', models.PositiveIntegerField()),
                ('parent_local_id', models.CharField(blank=True, max_length=32, null=True)),
                ('child_local_ids', models.JSONField(blank=True, default=list)),
                ('is_compound_list', models.BooleanField(default=False)),
                ('lead_in_text', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('composite_text', models.TextField(blank=True, default='')),
                ('paragraph_ids', models.JSONField(blank=True, default=list)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='document_pipeline.extractedclause')),
                ('chunk_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='document_pipeline.chunkrun')),
            ],
            options={
                'db_table': 'chunks',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='chunkrun',
            index=models.Index(fields=['extraction_run', '-created_at'], name='chunkrun_run_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkrun',
            index=models.Index(fields=['chunker_version'], name='chunkrun_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunkrun',
            constraint=models.UniqueConstraint(fields=('extraction_run', 'attempt'), name='unique_chunk_run_attempt'),
        ),
        migrations.AddConstraint(
            model_name='chunkrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('extraction_run',), name='unique_current_chunk_run'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['chunk_run', 'order_index'], name='chunk_run_order_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['chunk_run', 'kind'], name='chunk_run_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['clause'], name='chunk_clause_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(condition=models.Q(('indexed_for_retrieval', True)), fields=['chunk_run', 'order_index'], name='chunk_run_indexed_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('chunk_run', 'local_id'), name='unique_chunk_local_id'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('chunk_run', 'order_index'), name='unique_chunk_order'),
        ),
    ]
