# Generated by Django 5.2.17 on 2026-09-22 10:39

import django.db.models.deletion
import document_pipeline.models.review_draft
import document_pipeline.models.workspace_lock
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_user_username_user_last_login_user_role_and_more'),
        ('document_pipeline', '0006_document_on_clause_paragraph_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('data_ingestion', 'Data Ingestion'), ('data_staging', 'Data Staging'), ('data_parsing', 'Data Parsing'), ('data_classification', 'Data Classification'), ('user_interaction', 'User Interaction')], max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('actor_system', models.CharField(blank=True, default='', max_length=128)),
                ('summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_notes',
            },
        ),
        migrations.CreateModel(
            name='DocumentParagraphRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paragraph_id', models.CharField(max_length=64)),
                ('breadcrumb', models.JSONField(blank=True, default=list)),
                ('source_page', models.PositiveIntegerField(default=1)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('original_text', models.TextField()),
                ('reviewed_text', models.TextField()),
                ('label', models.CharField(choices=[('Clause', 'Clause'), ('Non-clause', 'Non-clause')], default='Clause', max_length=16)),
                ('canonical_type', models.CharField(blank=True, default='', max_length=255)),
                ('sub_type', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('llm_issues', models.JSONField(blank=True, default=list)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=False)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('vector_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_paragraph_records',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_payload', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=document_pipeline.models.review_draft.default_draft_expiry)),
            ],
            options={
                'db_table': 'review_drafts',
            },
        ),
        migrations.CreateModel(
            name='VectorSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_differential', models.BooleanField(default=False)),
                ('records_total', models.PositiveIntegerField(default=0)),
                ('records_embedded', models.PositiveIntegerField(default=0)),
                ('records_unchanged', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='succeeded', max_length=16)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vector_sync_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=document_pipeline.models.workspace_lock.default_expiry)),
            ],
            options={
                'db_table': 'workspace_locks',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_under_review', to='core.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='review_status',
            field=models.CharField(choices=[('pending_classification', 'Pending Classification'), ('needs_review', 'Needs Review'), ('in_review', 'In Review'), ('draft', 'Draft'), ('reviewed', 'Reviewed'), ('published', 'Published'), ('reopened_in_review', 'Re-opened (In Review)'), ('reopened_reviewed', 'Re-opened (Reviewed)')], default='pending_classification', max_length=32),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['review_status'], name='doc_review_status_idx'),
        ),
        migrations.AddField(
            model_name='documentactivitylog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_activity', to='core.user'),
        ),
        migrations.AddField(
            model_name='documentactivitylog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='document_pipeline.document'),
        ),
        migrations.AddField(
            model_name='documentnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_notes', to='core.user'),
        ),
        migrations.AddField(
            model_name='documentnote',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='document_pipeline.document'),
        ),
        migrations.AddField(
            model_name='documentparagraphrecord',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragraph_records', to='document_pipeline.chunk'),
        ),
        migrations.AddField(
            model_name='documentparagraphrecord',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragraph_records', to='document_pipeline.classification'),
        ),
        migrations.AddField(
            model_name='documentparagraphrecord',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_records', to='document_pipeline.document'),
        ),
        migrations.AddField(
            model_name='documentparagraphrecord',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_paragraphs', to='core.user'),
        ),
        migrations.AddField(
            model_name='documentparagraphrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_paragraphs', to='core.user'),
        ),
        migrations.AddField(
            model_name='reviewdraft',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_drafts', to='document_pipeline.document'),
        ),
        migrations.AddField(
            model_name='reviewdraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_drafts', to='core.user'),
        ),
        migrations.AddField(
            model_name='vectorsyncrun',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_sync_runs', to='document_pipeline.document'),
        ),
        migrations.AddField(
            model_name='vectorsyncrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vector_sync_runs', to='core.user'),
        ),
        migrations.AddField(
            model_name='workspacelock',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_lock', to='document_pipeline.document'),
        ),
        migrations.AddField(
            model_name='workspacelock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_locks', to='core.user'),
        ),
        migrations.AddIndex(
            model_name='documentactivitylog',
            index=models.Index(fields=['document', '-created_at'], name='actlog_doc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivitylog',
            index=models.Index(fields=['document', 'phase'], name='actlog_doc_phase_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivitylog',
            index=models.Index(fields=['actor_user', '-created_at'], name='actlog_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivitylog',
            index=models.Index(fields=['-created_at'], name='actlog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentparagraphrecord',
            index=models.Index(fields=['document', 'sequence_order'], name='dpr_doc_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='documentparagraphrecord',
            index=models.Index(fields=['document', 'is_reviewed'], name='dpr_doc_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='documentparagraphrecord',
            index=models.Index(fields=['document', 'is_modified'], name='dpr_doc_modified_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentparagraphrecord',
            constraint=models.UniqueConstraint(fields=('document', 'paragraph_id'), name='unique_paragraph_per_document'),
        ),
        migrations.AddIndex(
            model_name='reviewdraft',
            index=models.Index(fields=['document'], name='draft_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdraft',
            index=models.Index(fields=['expires_at'], name='draft_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewdraft',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='unique_draft_per_document_user'),
        ),
        migrations.AddIndex(
            model_name='vectorsyncrun',
            index=models.Index(fields=['document', '-started_at'], name='vsync_doc_started_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacelock',
            index=models.Index(fields=['document'], name='wslock_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacelock',
            index=models.Index(fields=['user'], name='wslock_user_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacelock',
            index=models.Index(fields=['expires_at'], name='wslock_expires_idx'),
        ),
    ]
