# Generated by Django 5.2.17 on 2026-09-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_pipeline', '0007_classification_paragraph_ids'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classification',
            name='classification_has_reason',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='reason',
        ),
    ]
