# Generated by Django 5.2.17 on 2026-09-22 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pipeline', '0008_remove_classification_classification_has_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accepted', 'accepted'), ('corrected', 'corrected'), ('rejected', 'rejected')], max_length=16)),
                ('label', models.CharField(blank=True, choices=[('Clause', 'Clause'), ('Non-clause', 'Non-clause')], max_length=16, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('reviewed_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='document_pipeline.canonicaltype')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='document_pipeline.classification')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='document_pipeline.classificationrun')),
            ],
            options={
                'db_table': 'classification_reviews',
                'indexes': [models.Index(condition=models.Q(('is_current', True)), fields=['run'], name='review_run_current_idx'), models.Index(fields=['classification', '-revision'], name='review_history_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('classification',), name='unique_current_review_per_classification'), models.CheckConstraint(condition=models.Q(models.Q(('canonical_type__isnull', False), ('decision', 'corrected')), models.Q(models.Q(('decision', 'corrected'), _negated=True), ('canonical_type__isnull', True)), _connector='OR'), name='review_type_iff_corrected'), models.CheckConstraint(condition=models.Q(models.Q(('decision', 'rejected'), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='review_rejected_has_note'), models.CheckConstraint(condition=models.Q(models.Q(('label', 'Non-clause'), _negated=True), ('sub_type__isnull', True), _connector='OR'), name='review_non_clause_has_no_sub_type'), models.UniqueConstraint(fields=('classification', 'revision'), name='unique_review_revision')],
            },
        ),
    ]
