# Generated by Django 5.2.17 on 2026-09-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_pipeline', '0007_review_workspace'),
        ('document_pipeline', '0009_classificationreview'),
    ]

    operations = [
    ]
