# Generated by Django 5.2.17 on 2026-09-23 06:01

import django.db.models.deletion
from django.db import migrations, models


def backfill_documents(apps, schema_editor):
    ChunkRun = apps.get_model('document_pipeline', 'ChunkRun')
    Classification = apps.get_model('document_pipeline', 'Classification')
    ClassificationCall = apps.get_model('document_pipeline', 'ClassificationCall')
    ClassificationReview = apps.get_model('document_pipeline', 'ClassificationReview')

    for row in ChunkRun.objects.select_related('extraction_run').iterator():
        row.document_id = row.extraction_run.document_id
        row.save(update_fields=['document'])
    for row in Classification.objects.select_related('run').iterator():
        row.document_id = row.run.document_id
        row.save(update_fields=['document'])
    for row in ClassificationCall.objects.select_related('run').iterator():
        row.document_id = row.run.document_id
        row.save(update_fields=['document'])
    for row in ClassificationReview.objects.select_related('run').iterator():
        row.document_id = row.run.document_id
        row.save(update_fields=['document'])


class Migration(migrations.Migration):

    dependencies = [
        ('document_pipeline', '0010_merge_0007_review_workspace_0009_classificationreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkrun',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunk_runs', to='document_pipeline.document'),
        ),
        migrations.AddField(
            model_name='classification',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='document_pipeline.document'),
        ),
        migrations.AddField(
            model_name='classificationcall',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_calls', to='document_pipeline.document'),
        ),
        migrations.AddField(
            model_name='classificationreview',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_reviews', to='document_pipeline.document'),
        ),
        migrations.RunPython(backfill_documents, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='chunkrun',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_runs', to='document_pipeline.document'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='document_pipeline.document'),
        ),
        migrations.AlterField(
            model_name='classificationcall',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_calls', to='document_pipeline.document'),
        ),
        migrations.AlterField(
            model_name='classificationreview',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_reviews', to='document_pipeline.document'),
        ),
    ]
