# Generated by Django 5.2.17 on 2026-10-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pipeline', '0017_classification_text_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='agreement_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='sectorial_category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
